# Generated by Django 4.2.7 on 2023-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('nota', models.CharField(max_length=200)),
                ('Fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
